### PR TITLE
Ensures availability of unzip & yq; Updates yq commands for v4

### LINKED ISSUE #50: setup_nfs_provisioner not fully automated
Here are a few issues with the this `utils/setup_nfs_provisioner.sh` script:

a) Does not install unzip with is required.
b) Does not pull a version of yq for ppc64le
c) yq fails to parse deployment.yaml

```
./setup_nfs_provisioner.sh: line 82: unzip: command not found
./setup_nfs_provisioner.sh: line 84: cd: external-storage-master/nfs-client/: No such file or directory
INFO: generating deployment.yaml for ppc64le...
./setup_nfs_provisioner.sh: line 107: deploy/deployment-ppc64le.yaml: No such file or directory
ERROR: failed to update deployment.yaml -- aborting...
```

After installing unzip and yq:

```
[root@rdr-rhop-f5d9a8-mon01-bastion-0 utils]# ./setup_nfs_provisioner.sh  /home/nfsshare  192.168.0.204
./setup_nfs_provisioner.sh: line 29: [: argument expected
INFO: proceeding with making this node as NFS server...
Last metadata expiration check: 1 day, 1:09:33 ago on Thu 30 Sep 2021 01:19:56 PM UTC.
Package nfs-utils-1:2.3.3-41.el8_4.2.ppc64le is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Warning: ALREADY_ENABLED: nfs
success
Warning: ALREADY_ENABLED: rpc-bind
success
Warning: ALREADY_ENABLED: mountd
success
success
INFO: downloading and extracting external-storage zip...
INFO: generating deployment.yaml for ppc64le...
Error: unknown command "write" for "yq"
Run 'yq --help' for usage.
ERROR: failed to update deployment.yaml -- aborting...
```

### PR DESCRIPTION
**Pull request by miyamotoh**
Fixes #50, tested on RHEL 8.4 on ppc64le

Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>

### CODE REVIEW

File: utils/setup_nfs_provisioner.sh [hunk 1]
```diff
@@ -76,38 +76,44 @@ THEZIP=kubernetes-incubator.zip
 curl -s -L -o $THEZIP https://github.com/kubernetes-incubator/external-storage/archive/master.zip
 if [ $? -ne 0 ]; then
 	echo "ERROR: failed to download external storage zip -- aborting..."
-	exit 6
+	exit 8
 fi
 
+which unzip 2>&1 >/dev/null || yum -y install unzip
```
Comment (hamzy) [inline utils/setup_nfs_provisioner.sh:82]: nit `hash` also tests for the existence of an executable and also updates bash's cache of where programs are located.

Comment (miyamotoh) [reply utils/setup_nfs_provisioner.sh:82]: While refreshing bash's cache with a new search may not be much, I like `hash` is silent in stdout, and I wouldn't have to do the `>/dev/null` thing. Will update my PR.

**Comment by yussufsh** [comment]
This was pending from long I went ahead and merged this.
